name: Webstore Publish

on:
  push:
    branches: 
      master

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1.1
        with:
          files: src
          dest: src.zip
      - uses: actions/upload-artifact@v2
        with:
          name: livechart-plus-${{ github.event_name }}
          path: src.zip
  build:
    name: Publish webextension
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - uses: actions/download-artifact@v3
      with:
        name: livechart-plus-${{ github.event_name }}
    - name: Upload & release
      uses: mnao305/chrome-extension-upload@v4.0.1
      with:
        file-path: src.zip
        publish: true
        extension-id: ${{vars.extensionId}}
        client-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        refresh-token: ${{ secrets.REFRESH_TOKEN }}
